### ISSUE TITLE
O1.2.1 (part of) GPU support for CloudMicrophysics.jl

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#164]
### Objective
Make all CloudMicrophysics.jl functions GPU compatible.

### People and Personnel
- Lead: @sriharshakandala 
- Collaborators: @trontrytel 
- Reviewers: @simonbyrne

### Components
- CloudMicrophysics.jl already has tests that run on the GPU. The majority of functions are simple point-wise functions that should not pose any issues.
- Might benefit from refactoring how we handle the parameter struct.
- The only thing we really need to decide right now is how to handle asserts and warnings. 

### Inputs
- Decide how to handle asserts and warnings for when someone is calling a parameterization outside of it's accepted range of inputs.

### Results and Deliverables
- Do we want to have above 90% GPU test code coverage? Or is that an overkill, given that we have a very high CPU test coverage? Is it enough for the GPU tests to test an example function from each module?

### Task Breakdown And Schedule
Going through the modules in the order of how we will need them:
- [x] https://github.com/CliMA/CloudMicrophysics.jl/issues/160
- [x] #199
- [x] #219
- [x] https://github.com/CliMA/CloudMicrophysics.jl/issues/153
- [x] https://github.com/CliMA/CloudMicrophysics.jl/issues/242
- [x] #233
- [x] https://github.com/CliMA/CloudMicrophysics.jl/issues/177

Additional items (would be nice, but not strictly necessary)
- [x] https://github.com/CliMA/CloudMicrophysics.jl/issues/173
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/234

### CC
@tapios @simonbyrne @cmbengue

**Comment by trontrytel** [comment]
Think if we can use any of the ideas here:
- https://github.com/CliMA/Thermodynamics.jl/pull/158
- https://github.com/CliMA/Thermodynamics.jl/blob/main/src/DataCollection.jl

To be able to preserve the information on when someone is trying to call parameterizations outside of their range

**Comment by trontrytel** [comment]
Checking this as done.

Tackling the logging will take longer and it's not immediately needed to run on the GPU
