### ISSUE TITLE
O1.3.2 Data driven aerosol activation scheme

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#214]
We want to optionally include the data-driven aerosol activation parameterizations in the package.

```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/181
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/348
- [x] Add documentation about the extensions
- [x] Add options for informing the emulators with additional features from ARG
```

**Comment by trontrytel** [comment]
We have all the emulators available. The training is tested in a longruns pipeline.

At some point we will also add an EKI calibration example, but it doesn't have to be tracked under this issue.
