### ISSUE TITLE
Breakup the parameter struct 

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#247]
Continuing the work from https://github.com/CliMA/CloudMicrophysics.jl/issues/160

The remaining modules:
```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/252
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/255
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/260
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/261
- [x] Breakup parameters in Aerosol nucleation
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/265
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/pull/264
```

**Comment by trontrytel** [comment]
This is done. We will have a release soon
