### ISSUE TITLE
Single column testing

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#359]
## Software Design Issue

Conduct a series of single column kinematic model tests for different CloudMicrophysics schemes. (It's easier to test and debug things than in ClimaAtmos).

```[tasklist]
### Tasks
- [ ] Bring back Kinematic1D CI
- [ ] Change Kinematic1D repo name
- [ ] Add documentation to Kinematic1D model driver
- [ ] Refactor Kinematic1D model code (get rid of repetitions in defining tendencies for different model configurations)
- [ ] Add documentation to Kinematic1D model calibrations
- [ ] Show simulations with ARG and ML ARG activation
- [ ] Show simulations with different ice nucleation parameterizations
- [ ] Show simulations with P3 scheme
```

### CC
@tapios @cmbengue

**Comment by tapios** [comment]
Looks good to me.
