### ISSUE TITLE
Implement the Aerosol Model

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#85]
## Purpose
Implement the MAM3 (with easy extensions to 4/7) aerosol model. See https://gmd.copernicus.org/articles/5/709/2012/ and https://gmd.copernicus.org/articles/9/505/2016/gmd-9-505-2016.pdf

## Cost/Benefits/Risks
We need an aerosol model. We don't have in-house expertise and manpower to develop a new one. We want to implement the widely used MAM, but in a way that refactors and makes the code modular. We don't know (yet) how much code needs to be refactored and how many empirical parameterisations we will be adding to our code base.

## People and Personnel
- Lead: @nefrathenrici 
- Collaborators: @trontrytel, @szy21
- Reviewers: @tapios, @charleskawczynski 

## Results and deliverables
To be added after Dec 5th meeting.

## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [x] Prepare for discussion of the implementation strategy (using the above 3 examples to show how the code looks) on Dec 5th.
- [x] Research how to approximate the formation energies in nucleation parameterisation. This would allow us to keep the functional form of Arrhenius equation and help with the interpretability of free parameters.
- [ ] #86
- [ ] #87
- [ ] Add nucleation (code and docs): https://github.com/CliMA/CloudMicrophysics.jl/pull/84
- [ ] #91
- [ ] Replace the simplified analytical integrals of the coagulation parameterisation with numerical integrals of the full kernel using quadrature points. This would get rid of thousands of correction coefficients as well as make the code more flexible to changing the coagulation kernels. 
- [ ] Add a performance test for ClimaAtmos.jl to estimate the computational cost of advecting all the tracers.
- [ ] Define unit tests for coagulation parameterization.
- [ ] Define functionality tests we want to check.
- [ ] Define the milestone simulations we want to run.
- [ ] Get CAM running on the cluster

## Proposed Delivery Date
Delivery date to be added after the Dec 5th discussion.

**Comment by szy21** [comment]
Thanks Anna, I would be happy to join the discussion and help!

**Comment by trontrytel** [comment]
> Thanks Anna, I would be happy to join the discussion and help!

Thanks! Thats great! We will need to figure out the explanation for many of the aerosol model parameterisations before merging them in. So that we understand where all our free parameters are coming from. It would be great to have your 👀 there for sure

**Comment by tapios** [comment]
Looks good. I like the emphasis on clean documentation--that will be helpful for me.

**Comment by trontrytel** [comment]
Closing. We have moved the plan to https://github.com/CliMA/CloudMicrophysics.jl/issues/96
