### ISSUE TITLE
Add a parameterization of water vapour deposition on dust

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#89]
## Purpose
Add a parameterization of water vapour deposition on dust particles. This is an example of heterogeneous ice nucleation.

## Cost/Benefits/Risks
TBD

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: Amy 
- Collaborators: @trontrytel 
- Reviewers: @trontrytel , @szy21 , @tapios 

## Components
TBD

## Inputs
(Describe the inputs to the software solution)

## Results and deliverables
(Summarize of the key results, deliverables, quality expectations, and performance metrics)

## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [x] Derive the equations needed to compute the activated fraction. Show examples from literature of different parameterizations.
- [x] Write down the documentation for the activated fraction function
- [x] Implement the activated fraction. Add unit tests.
- [x] Add the box model test case from Tully et al 2022.
- [ ] ~~Add the cumulative vs differential way of integrating activated fraction parameterization in time.~~

## Proposed Delivery Date
(Your best estimate of the date this software solution will be completed)

**Comment by tapios** [comment]
Looks good. But let's talk with Amy about how comfortable she is with this program.
