### ISSUE TITLE
Aerosol Model

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#96]
### Background
End-goal: Implement the MAM3 (with easy extensions to 4/7) aerosol model. See [MAM3/7](https://gmd.copernicus.org/articles/5/709/2012/) and [MAM4](https://gmd.copernicus.org/articles/9/505/2016/gmd-9-505-2016.pdf) for more background.

We need an aerosol model. We don't have in-house expertise and manpower to develop a new one, but we have been relying on advice from the Atmospheric Chemistry group. We want to implement the widely used MAM, but in a way that refactors and makes the code modular. We don't know (yet) how much code needs to be refactored and how many empirical parameterisations we will be adding to our code base.

#### Attributes:
 - [ ] Modular processes: We should be able to switch different processes on/off (e.g. nucleation pathways).
 - [ ] Documentation: Clear explanations tying theory to code, as well as use examples.
 - [ ] Explanation of coupling with CloudMicrophysics and EDMF
 - [ ] Expand ClimaParameters to include aerosol properties and chemical parameters (molar mass, density, reaction rates).
#### Testing Attributes: 
 - [ ] Unit tests for individual processes, reproducing results from papers
 - [ ] Functionality tests: simple overall testing coupled with EDMF
 - [ ] End-to-end comparison tests with CAM
 - [ ] Performance testing in ClimaAtmos

#### Stretch Goals:
We will aim for these, but want to get MAM3 working first.
 - [ ] Flexible modes: We should be able to test different modal resolutions (MAM3, 4, and 7). 
 - [ ] GPU testing

### Constraints
 - [ ] Avoid introducing large numbers of free parameters (possible metric: free-parameter/locs). This can mean rewriting MAM3 processes causing longer development times.
 - [ ] What is an acceptable time and memory cost increase from the aerosol model within ClimaAtmos?

### Benefits
 - [ ] We will have an aerosol model!
 - [ ] Well-documented and interpretable addition to the atmosphere model (hopefully without too much performance cost).

### Implementation Details
The basic aerosol distribution data structure is already given in CloudMicrophysics.jl, and will be expanded upon as needed.
This data structure will act as the central source of information, and will be modified at each timestep by the different processes.
The different processes which will be modeled are:
#### Nucleation
 - New particle formation via clustering of trace gases. Newly formed particles are added to the Aitken mode, since there is no nucleation mode. 
 - This is currently parameterized via Dunne et al., 2016, based on the CLOUD experiments. 
 - This is [nearly complete](https://github.com/CliMA/CloudMicrophysics.jl/pull/84)
#### Coagulation
 - Binary particle collision calculated for the Aitken and Accumulation modes. 
 - Intramodal collision increases particle diameter and decreases number concentration. Intermodal collision increases particle diameter and mass of the larger mode, and decreases mass and number concentration of the smaller mode.
 - Calculated via integration over the modal distributions. Integration is approximated via numerical quadrature, using the Cubature.jl package.
 All processes below have not been thoroughly investigated and may be subject to change.
#### Condensation
 - Phase change of trace gases onto existing particles. 
 - Calculated for each mode via standard mass transfer expressions (Seinfeld and Pandis, 1998), then integrated over the modal distributions.
 - H2SO4, NH3 condensation are irreversible, SOA condensation is reversible.
####  Emissions
 - This will hopefully be straightforward, as particle emission rates can be taken from datasets. 
 - The IPCC AR5 dataset includes anthropogenic emission fluxes for primary aerosol species and precursor gases: organic carbon, black carbon, and SO2.
 - The AeroCom datasets include injection heights and size distributions of primary emitted particles and precusor gases.
 - The AeroCom datasets also include emission fluxes, injection heights, and size distributions for volcanic SO2, sulfate, and surface dimethyl sulfate flux.
 - The MOZART-4 dataset includes emission fluxes for NH3, isoprene, monoterpenes, toluene, big alkenes, and big alkanes.
 - Sea salt aerosol emissions from the ocean are parameterized by Martensson et al.,2003 (https://doi.org/10.1029/2002JD002263)
 - Mineral dust particle emissions are calculated based on the Dust Entrainment and Deposition Model from Zender et al., 2003 (doi:4410.1029/2002JD002775)
#### Sulfur species gas-phase chemistry
 - Dimethyl sulfate oxidation by OH and NO3 to form SO2
 - SO2 oxidation by OH to form H2SO4
 - HO2+HO2 to H2O2 production
 - H2O2 loss via H2O2 photolysis and H2O2+OH
 - The above all use rate coefficients from MOZART-4 from Emmons et al., 2010
 - Oxidant concentrations are interpolated from monthly averages taken from CAM-Chem (Lamarque et al., 2010)
 - SO2 oxidation in bulk cloud water comes from the MOZART treatment from Tie et al., 2001
 - Irreversible H2SO4 gas uptake is calculated from Seinfeld and Pandis, 1998
 - Sulfate (produced from SO2 aqueous oxidation) and H2SO4 gas uptake are partitioned to increase sulfate mixing ratio in each mode according to the cloud droplet number for each mode
#### Removal
 - In-cloud scavenging: First-order removal rates for cloud water will come from precipitation production rates and cloud water mixing ratios.
 - Below-cloud scavenging: First-order removal rates will come from precipitation rate. The scavenging coefficient is calculated from Wang et al., 2011 (Equation 2)
 - Dry deposition velocities are calculated from Zhang et al., 2001.
 - Gravitational settling velocities are calculated from Seinfeld and Pandis, 1998
 - In the MAM specification, wet particle size is calculated from average aerosol mass and number.
 - Aerosol mixing ratio changes and fluxes from dry deposition are calculated from Zender et al., 2003.
#### Secondary Organic Aerosol
 - Assume fixed percentage mass yield of precursor volatile organic compounds (VOCs)
 - Include a single lumped semi-volatile organics gas-phase species (MAM refers to this as SOAG)
 - Assume percentage mass yields of precursor VOCs to form SOAG
 - Condensation and evaporation of SOAG to/from aerosol modes will be handled by the condensation process.
 #### Vertical transport will be handled by coupling to EDMF
 #### Radiation is also planned to be coupled to RRTMGP

### Preliminary Deliverables
 - [ ] [Documentation for overall model aerosol size distribution representation](https://github.com/CliMA/CloudMicrophysics.jl/issues/86)
 - [ ] [Documentation for solved equations and full list of processes](https://github.com/CliMA/CloudMicrophysics.jl/issues/87)
 - [ ] [Nucleation representation as guided by CLOUD experiments](https://github.com/CliMA/CloudMicrophysics.jl/issues/93)
 - [ ] Unit tests comparing nucleation to CLOUD data and Vehkamaki plots
 - [ ] [Coagulation representation calculated via numerical integrals](https://github.com/CliMA/CloudMicrophysics.jl/issues/91)
 - [ ] Coagulation unit tests comparing rates to the integral approximations found in Whitby et al., 1991

### Timeline and Deliverables
This only lists the basic timeline. As we more thoroughly investigate each process, specific testing needs and constraints will become clear.
The majority of time will be spent looking into each process to determine effectiveness and feasibility of the provided methods. If the provided methods are not compatible with our requirements, we will have to spent extra time finding and valdiating a new solution.
 - [ ] 3/17/23: Documentation and implementation plan for condensation process
 - [ ] 3/31/23: Code and testing for condensation
 - [ ] 4/31/23: Documentation and implementation plan for emissions, including sources and modifications
 - [ ] 5/14/23: Code and testing for emissions
 - [ ] 6/14/23: Documentation and implementation plan for each modelled chemical reaction 
 - [ ] 6/31/23: Code and testing for chemistry module completed

### Risks
The primary risk is that methods used in MAM may not be feasible or rigorous enough for our model. This has already been an issue with the implementations of nucleation and coagulation. The underlying methods for both of these were either outdated or not physically based, costing significant amounts of time. I have been generous with my timeline to try and account for this.

The secondary risk for the overall model development is verifying the correctness of our implementation. This is currently an issue with the coagulation process, as there are no readily available standalone tests for comparison. If we resort to comparing by with a full-scale model like CAM, it may be difficult to determine which process in our implementation is causing issues.

For emissions, it may be challenging to acquire all of the necessary datasets. If we are missing some, it will be time consuming to find alternatives.

Implemented by: @nefrathenrici @trontrytel
Proposed Start Date: 11/2022

### Metadata
Proposed by: @trontrytel @nefrathenrici
Proposal Date: 12/2022

***
Reviewed by: @tapios 
Date of Review: 2023-02-16

### CC
@tapios @simonbyrne @cmbengue

**Comment by tapios** [comment]
This looks great! Very detailed and thorough, with the understanding that this is a complex problem and we'll likely have to adapt the plans as we go and learn more.
